### ISSUE TITLE
Error in wgpu_queue_write_texture and wgpu_queue_copy_external_image_to_texture

### ISSUE THREAD

**Issue by brendan-duncan** [juj/wasm_webgpu#1]
They get the WGpuImageCopyTexture destination object as `wgpu[destination]`, but it's not a stored object. It should probably get it with `wgpuReadGpuImageCopyTexture(destination)`.

**Comment by juj** [comment]
Good catch. Pushed a fix in above commit, though untested, as I don't currently have a test sample written up for that yet.
