### ISSUE TITLE
wgpu_device_create_buffer should set isBuffer

### ISSUE THREAD

**Issue by brendan-duncan** [juj/wasm_webgpu#10]
wgpu_device_create_bind_group checks if the resource is a buffer by looking at isBuffer, but it's never set for a buffer. I'd think it should be set when the buffer is created.

Thanks for all the help updating the library, hope you don't bind all the issue submissions. I'm inching forward by making local fixes, want to make sure I don't loose track of any fixes, and figured you'd like to keep the official version changes in your own style versus a PR.

**Comment by juj** [comment]
Ops, adding that was in the back of my mind, but of course it slipped..

I don't mind at all the issue submissions, thanks for posting them!
