### ISSUE TITLE
wgpu_buffer_get_mapped_range

### ISSUE THREAD

**Issue by brendan-duncan** [juj/wasm_webgpu#12]
If size is not provided, it passes `void 0` to getMappedRange, but that doesn't seem to work and results in a 0 sized range. An option is to conditionally call getMappedRange on size being set or not.

```
if (size)
    gpuBuffer.mappedRanges[offset] = gpuBuffer["getMappedRange"](offset, size);
else
    gpuBuffer.mappedRanges[offset] = gpuBuffer["getMappedRange"](offset);
```

**Comment by juj** [comment]
Thanks - some other APIs have this same issue. Marking these kinds of issues with a common label "Awkward polymorphism" to find them easier, maybe the spec might be able to adapt to accommodate for some of these.

Btw, pushed a breaking commit that completes renaming of GPUCanvasContext to GPUPresentationContext, so the function `wgpu_canvas_get_canvas_context()` is now renamed to `wgpu_canvas_get_gpupresent_context()`.
