### ISSUE TITLE
WGpuRenderPipelineDescriptor missing layout, plus some minor cleanups

### ISSUE THREAD

**Issue by brendan-duncan** [juj/wasm_webgpu#15]
`WGpuRenderPipelineDescriptor` is supposed to derive from `GPUPipelineDescriptorBase` and have a `GPUPipelineLayout layout` member.

`WGPU_INPUT_STEP_MODE` should probably be `WGPU_VERTEX_STEP_MODE` now, to match the new name of the string constants.

Some other minor cleanups:
WGpuBindGroupLayoutDescriptor and similarly removed structs are still defined in lib_webgpu_fwd.h

**Comment by juj** [comment]
Fixed in above commit.

Also noticed that the module creation code was missing the shader constants dictionary.
