### ISSUE TITLE
Why do you need to implement your own C++ lib webgpu?

### ISSUE THREAD

**Issue by zhangwei983** [juj/wasm_webgpu#18]
I managed to run the samples locally, it's pretty cool!

But one question came into my mind is that why you need to implement your own C++ lib webgpu, instead of using the one used by emscripten https://github.com/emscripten-core/emscripten/blob/main/system/include/webgpu/webgpu.h ?

**Comment by alienself** [comment]
Same question here. 

I saw that this repo supports `importExternalTexture` to load textures outside of the wasm module which is not available on the official emscripten lib. 

@juj Will this work land in the official lib or are you planning to maintain this library in parallel?

**Comment by juj** [comment]
The rationale for writing my own bindings layer is referenced in [this emscripten-discuss mailing list thread](https://groups.google.com/g/emscripten-discuss/c/vqmODp_je1Q), and also in the main README.md of this repository.

I maintain the original WebGL and WebGL 2 bindings in Emscripten, and its MINIMAL_RUNTIME feature, so the experience from those two initiatives resulted in a very particular desire for how the bindings layer should look for our purposes.

For now I am maintaining this library separately. I regularly chat with Kai and Shrek at Google who develop the upstream Emscripten bindings, though there hasn't been a strong rationale to replace the upstream library at this point.

**Comment by zhangwei983** [comment]
Thanks for the explanation, I'll close this issue then.
