### ISSUE TITLE
What is `_wgpu_object_destroy`

### ISSUE THREAD

**Issue by yowl** [juj/wasm_webgpu#26]
Can I ask what and where this is defined?  It appears in
https://github.com/juj/wasm_webgpu/blob/720035d02dff54f4957351a7c990ed640b6f9a17/lib/lib_webgpu.js#L2123
Should it actually be `wgpu_object_destroy`  as it appears to be undefined
![image](https://user-images.githubusercontent.com/2720041/214872824-1f133498-bc90-42cd-9fbe-53c516f3f042.png)

**Comment by juj** [comment]
Thanks, these were missing dependencies in the code (the compute path only section is quite untested, as you are observing). Fixed in https://github.com/juj/wasm_webgpu/commit/d6923bbc32d880aef162e808ea37adfda43e4b85

**Comment by yowl** [comment]
Awesome, I was just looking at `__deps` .  Thanks!
