### ISSUE TITLE
Question: Chrome origin trial

### ISSUE THREAD

**Issue by yowl** [juj/wasm_webgpu#28]
Everything is great with the flag on, but with the origin trial `meta http-equiv="origin-trial"` header, My page (https://yowl.github.io/Particles/) just never gets a response, error or callback from `wgpu[adapter]['requestDevice'](`  .  Just wanted to ask if anyone has experience of the origin trial working?

**Comment by juj** [comment]
I haven't tried the origin trial, just been developing with the `--enable-unsafe-webgpu` flag. I wonder if @kainino0x might know: is the WebGPU origin trial currently active and should work?

**Comment by juj** [comment]
When I visit the page on my stock Google Chrome without the `--enable-unsafe-webgpu` flag, I do get the page loading ok:

![image](https://user-images.githubusercontent.com/225351/215140803-c3740e2f-7424-4142-b679-9fcb0b89286b.png)

I think that should be then hitting the origin trial, I am pretty sure my stable Chrome shouldn't run on a custom flag, I only have the flag on when using Chrome Canary.

**Comment by juj** [comment]
When I run the page in my stable Google Chrome, it runs ok:

![image](https://user-images.githubusercontent.com/225351/215141348-ffb6bc79-1782-49e0-8b81-d3f8479b602f.png)

That should not have the `--enable-unsafe-webgpu` flag in there. Maybe the origin trial took a moment to register?

**Comment by yowl** [comment]
ok, thanks.  I will try stable as I was using canary.
