### ISSUE TITLE
wgpu_device_create_pipeline_layout fails with "assert(wgpu[HEAPU32[ptr]]) failed"

### ISSUE THREAD

**Issue by patrickinminneapolis** [juj/wasm_webgpu#34]
I am trying to implement generic matrix multiplication from this repo, [webgpu-blas](https://github.com/milhidaka/webgpu-blas )

My call to `wgpu_device_create_pipeline_layout`  fails.  I'm probably doing something wrong, I apologize, does anyone see any glaring problems with my setup of `wgpu_device_create_pipeline_layout`  ?
```

 WGpuBindGroupLayoutEntry bindGroupLayoutEntries [4];
    for (uint32_t i = 0; i < 4; i++) {  
        WGpuBindGroupLayoutEntry tmpBinding = {};
        tmpBinding.binding = i;
        tmpBinding.visibility = 0x4; 
        tmpBinding.type = bindingTypes[i]; 
        bindGroupLayoutEntries[i] = tmpBinding;
    }

    const WGpuBindGroupLayout bindGroupLayout = wgpu_device_create_bind_group_layout(device, bindGroupLayoutEntries, 4);
        WGpuPipelineLayout pipelineLayout = wgpu_device_create_pipeline_layout(device, &bindGroupLayout, 4);
```

> 
>     wgpu_device_create_pipeline_layout(device=4, layouts=643008, numLayouts=4)
>     helpers.js:14 Aborted(assert(wgpu[HEAPU32[ptr]]) failed!)
>     stream.js:1 Uncaught (in promise) RuntimeError: Aborted(assert(wgpu[HEAPU32[ptr]]) failed!). Build with -sASSERTIONS for more info.
>     at abort (stream.js:1:9834)
>     at assert (stream.js:1:4751)
>     at wgpuReadArrayOfWgpuObjects (stream.js:1:605471)
>     at _wgpu_device_create_pipeline_layout (stream.js:1:614798)
>     at 00169262:0x448dd
>     at stream.js:1:605062

**Comment by juj** [comment]
The call

```
wgpu_device_create_pipeline_layout(device, &bindGroupLayout, 4);
```
specifies that there would be an array of four bind group layouts, `bindGroupLayout[0], bindGroupLayout[1], bindGroupLayout[2]` and `bindGroupLayout[3]` to read, but the code only created one BindGroupLayout.

Maybe you intended to call `wgpu_device_create_pipeline_layout(device, &bindGroupLayout, 1);` instead?

**Comment by patrickinminneapolis** [comment]
Ah, yes.  Thanks for your help.
