### ISSUE TITLE
Samples don't compile with the provided instructions

### ISSUE THREAD

**Issue by gahaas** [juj/wasm_webgpu#50]
I tried to compile the samples with the instructions provided in README.md, but I failed, see https://pastebin.com/EsKCsfTJ. As far as I can tell I followed the instructions precisely, so I wonder if there is something missing in the README.md.

**Comment by juj** [comment]
Thanks for reporting! I had not manually run the samples in a while, and it looks like the recent migration to use `alignas(8)` only works in C++11 and newer, and not for .c files. Fixed in above commit.

**Comment by gahaas** [comment]
Thanks, it compiles not for me!
