### ISSUE TITLE
Compile to WebGL?

### ISSUE THREAD

**Issue by munrocket** [juj/wasm_webgpu#51]
Is it possible to chose OpenGL ES backend and compile to wasm?

**Comment by juj** [comment]
No, this project is only for WebGPU, not for WebGL. For WebGL via OpenGL ES, you can use Emscripten.

**Comment by munrocket** [comment]
@juj do you think thar it is easy to make WebGPU [polyfill](https://github.com/CodyJasonBennett/webgpu-polyfill) with compat mode in Dawn?

Tint already compiled, but for WebGPU main difficulty probably will be “createRenderPipeline* function because it’s consumes object on JS side, but in webgpu.h it is separate functions, am I right?
