### ISSUE TITLE
wgpu_device_create_sampler

### ISSUE THREAD

**Issue by brendan-duncan** [juj/wasm_webgpu#6]
The spec is still messed up for GpuSamplerDescriptor.lodMaxClamp, and it seems Chrome messed it up even more by making it required to be a finite number. So the default `.lodMaxClamp = __builtin_inf()` throws an exception that lodMaxClamp needs to be finite.

**Comment by juj** [comment]
Adjusted the max clamp to 65536. That should allow for 2^65536 sized textures, far more than anything in existence. Left the TODO there, to adjust when the spec actually comes up with a good default.

I'd imagine the spec would have a value for "disable LOD clamping", it feels like hardware could reasonably have a faster path to sample a texture when lod clamping is not used at all.
