### ISSUE TITLE
wgpu_device_create_bind_group

### ISSUE THREAD

**Issue by brendan-duncan** [juj/wasm_webgpu#7]
return wgpuStoreAndSetParent(bindGroup, device);
should be
return wgpuStoreAndSetParent(bindGroup, wgpu[device]);

**Comment by brendan-duncan** [comment]
Think I might be mistaken about this.

**Comment by brendan-duncan** [comment]
Actually it is an issue, I was looking at the old version when I thought it might not be.

**Comment by brendan-duncan** [comment]
It seems a lot of the functions were changed to not cache the wgpu[device] and have the same issue.

**Comment by juj** [comment]
Fixed in above commit.
