### ISSUE TITLE
wgpu_device_create_bind_group doesn't support GPUBufferBinding

### ISSUE THREAD

**Issue by brendan-duncan** [juj/wasm_webgpu#8]
This function doesn't seem very well suited for a C interface with it's polymorphic input.

wgpu_device_create_pipeline_layout will have similar issues.

**Comment by juj** [comment]
Fixed wgpu_device_create_bind_group() in above commit. (though I don't have a test program) I am not sure I saw the issue with wgpu_device_create_pipeline_layout().
